name: Cypress Tests

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run once a day at 2am, 8am, and 12pm UTC
    # IST 7:30am, 1:30pm, 5:30pm
    - cron:  '0 2,8,12 * * *'

# * * * * *
# | | | | |
# | | | | └── Day of week (0 - 7) (Sunday is both 0 and 7)
# | | | └──── Month (1 - 12)
# | | └────── Day of month (1 - 31)
# | └──────── Hour (0 - 23)
# └────────── Minute (0 - 59)

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: npm install cypress -g


      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Run Cypress tests
        run: npx cypress-cloud run --parallel --record --key nBBNYte4xk5NLDiN --ci-build-id hello-currents


